/*
 * External method calls:
 *   Lnet/minecraft/enchantment/Enchantment;leveledCost(II)Lnet/minecraft/enchantment/Enchantment$Cost;
 *   Lnet/minecraft/enchantment/Enchantment;definition(Lnet/minecraft/registry/entry/RegistryEntryList;IILnet/minecraft/enchantment/Enchantment$Cost;Lnet/minecraft/enchantment/Enchantment$Cost;I[Lnet/minecraft/component/type/AttributeModifierSlot;)Lnet/minecraft/enchantment/Enchantment$Definition;
 *   Lnet/minecraft/enchantment/Enchantment;builder(Lnet/minecraft/enchantment/Enchantment$Definition;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;exclusiveSet(Lnet/minecraft/registry/entry/RegistryEntryList;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;linear(F)Lnet/minecraft/enchantment/EnchantmentLevelBasedValue$Linear;
 *   Lnet/minecraft/predicate/entity/DamageSourcePredicate$Builder;create()Lnet/minecraft/predicate/entity/DamageSourcePredicate$Builder;
 *   Lnet/minecraft/predicate/TagPredicate;unexpected(Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/TagPredicate;
 *   Lnet/minecraft/predicate/entity/DamageSourcePredicate$Builder;tag(Lnet/minecraft/predicate/TagPredicate;)Lnet/minecraft/predicate/entity/DamageSourcePredicate$Builder;
 *   Lnet/minecraft/loot/condition/DamageSourcePropertiesLootCondition;builder(Lnet/minecraft/predicate/entity/DamageSourcePredicate$Builder;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addEffect(Lnet/minecraft/component/ComponentType;Ljava/lang/Object;Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/predicate/TagPredicate;expected(Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/TagPredicate;
 *   Lnet/minecraft/loot/condition/AllOfLootCondition;builder([Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/loot/condition/AllOfLootCondition$Builder;
 *   Lnet/minecraft/util/Identifier;ofVanilla(Ljava/lang/String;)Lnet/minecraft/util/Identifier;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addEffect(Lnet/minecraft/component/ComponentType;Lnet/minecraft/enchantment/effect/AttributeEnchantmentEffect;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/enchantment/Enchantment;constantCost(I)Lnet/minecraft/enchantment/Enchantment$Cost;
 *   Lnet/minecraft/enchantment/Enchantment;definition(Lnet/minecraft/registry/entry/RegistryEntryList;Lnet/minecraft/registry/entry/RegistryEntryList;IILnet/minecraft/enchantment/Enchantment$Cost;Lnet/minecraft/enchantment/Enchantment$Cost;I[Lnet/minecraft/component/type/AttributeModifierSlot;)Lnet/minecraft/enchantment/Enchantment$Definition;
 *   Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;constant(F)Lnet/minecraft/enchantment/EnchantmentLevelBasedValue$Constant;
 *   Lnet/minecraft/enchantment/effect/AllOfEnchantmentEffects;allOf([Lnet/minecraft/enchantment/effect/EnchantmentEntityEffect;)Lnet/minecraft/enchantment/effect/AllOfEnchantmentEffects$EntityEffects;
 *   Lnet/minecraft/loot/provider/number/EnchantmentLevelLootNumberProvider;create(Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;)Lnet/minecraft/loot/provider/number/EnchantmentLevelLootNumberProvider;
 *   Lnet/minecraft/loot/condition/RandomChanceLootCondition;builder(Lnet/minecraft/loot/provider/number/LootNumberProvider;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addEffect(Lnet/minecraft/component/ComponentType;Lnet/minecraft/enchantment/effect/EnchantmentEffectTarget;Lnet/minecraft/enchantment/effect/EnchantmentEffectTarget;Ljava/lang/Object;Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;linear(FF)Lnet/minecraft/enchantment/EnchantmentLevelBasedValue$Linear;
 *   Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;matchingBlockTag(Lnet/minecraft/util/math/Vec3i;Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;
 *   Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;matchingBlocks([Lnet/minecraft/block/Block;)Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;
 *   Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;matchingFluids([Lnet/minecraft/fluid/Fluid;)Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;
 *   Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;unobstructed()Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;
 *   Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;allOf([Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;)Lnet/minecraft/world/gen/blockpredicate/BlockPredicate;
 *   Lnet/minecraft/world/gen/stateprovider/BlockStateProvider;of(Lnet/minecraft/block/Block;)Lnet/minecraft/world/gen/stateprovider/SimpleBlockStateProvider;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;create()Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;create()Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;onGround(Ljava/lang/Boolean;)Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;flags(Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/loot/condition/EntityPropertiesLootCondition;builder(Lnet/minecraft/loot/context/LootContext$EntityReference;Lnet/minecraft/predicate/entity/EntityPredicate$Builder;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;vehicle(Lnet/minecraft/predicate/entity/EntityPredicate$Builder;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/loot/condition/InvertedLootCondition;builder(Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addEffect(Lnet/minecraft/component/ComponentType;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;periodicTick(I)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;flying(Ljava/lang/Boolean;)Lnet/minecraft/predicate/entity/EntityFlagsPredicate$Builder;
 *   Lnet/minecraft/predicate/NumberRange$DoubleRange;atLeast(D)Lnet/minecraft/predicate/NumberRange$DoubleRange;
 *   Lnet/minecraft/predicate/entity/MovementPredicate;horizontalSpeed(Lnet/minecraft/predicate/NumberRange$DoubleRange;)Lnet/minecraft/predicate/entity/MovementPredicate;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;movement(Lnet/minecraft/predicate/entity/MovementPredicate;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/LocationPredicate$Builder;create()Lnet/minecraft/predicate/entity/LocationPredicate$Builder;
 *   Lnet/minecraft/predicate/BlockPredicate$Builder;create()Lnet/minecraft/predicate/BlockPredicate$Builder;
 *   Lnet/minecraft/predicate/BlockPredicate$Builder;tag(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/BlockPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/LocationPredicate$Builder;block(Lnet/minecraft/predicate/BlockPredicate$Builder;)Lnet/minecraft/predicate/entity/LocationPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;movementAffectedBy(Lnet/minecraft/predicate/entity/LocationPredicate$Builder;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/loot/condition/EnchantmentActiveCheckLootCondition;requireActive()Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;build()Lnet/minecraft/predicate/entity/EntityPredicate;
 *   Lnet/minecraft/loot/condition/EntityPropertiesLootCondition;builder(Lnet/minecraft/loot/context/LootContext$EntityReference;Lnet/minecraft/predicate/entity/EntityPredicate;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/loot/condition/AnyOfLootCondition;builder([Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/loot/condition/AnyOfLootCondition$Builder;
 *   Lnet/minecraft/loot/condition/EnchantmentActiveCheckLootCondition;requireInactive()Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/effect/AllOfEnchantmentEffects;allOf([Lnet/minecraft/enchantment/effect/EnchantmentLocationBasedEffect;)Lnet/minecraft/enchantment/effect/AllOfEnchantmentEffects$LocationBasedEffects;
 *   Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect;withinBoundingBox()Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect$PositionSource;
 *   Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect;entityPosition(F)Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect$PositionSource;
 *   Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect;scaledVelocity(F)Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect$VelocitySource;
 *   Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect;fixedVelocity(Lnet/minecraft/util/math/floatprovider/FloatProvider;)Lnet/minecraft/enchantment/effect/entity/SpawnParticlesEnchantmentEffect$VelocitySource;
 *   Lnet/minecraft/loot/condition/RandomChanceLootCondition;builder(F)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addEffect(Lnet/minecraft/component/ComponentType;Ljava/lang/Object;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/predicate/entity/EntityTypePredicate;create(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/entity/EntityTypePredicate;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;type(Lnet/minecraft/predicate/entity/EntityTypePredicate;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/registry/entry/RegistryEntryList;of([Lnet/minecraft/registry/entry/RegistryEntry;)Lnet/minecraft/registry/entry/RegistryEntryList$Direct;
 *   Lnet/minecraft/loot/condition/LootCondition$Builder;and(Lnet/minecraft/loot/condition/LootCondition$Builder;)Lnet/minecraft/loot/condition/AllOfLootCondition$Builder;
 *   Lnet/minecraft/predicate/entity/EntityTypePredicate;create(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/entity/EntityType;)Lnet/minecraft/predicate/entity/EntityTypePredicate;
 *   Lnet/minecraft/predicate/item/ItemPredicate$Builder;create()Lnet/minecraft/predicate/item/ItemPredicate$Builder;
 *   Lnet/minecraft/predicate/item/ItemPredicate$Builder;tag(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/item/ItemPredicate$Builder;
 *   Lnet/minecraft/loot/condition/MatchToolLootCondition;builder(Lnet/minecraft/predicate/item/ItemPredicate$Builder;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;type(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/registry/tag/TagKey;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/predicate/item/ItemPredicate$Builder;items(Lnet/minecraft/registry/RegistryEntryLookup;[Lnet/minecraft/item/ItemConvertible;)Lnet/minecraft/predicate/item/ItemPredicate$Builder;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;addNonListEffect(Lnet/minecraft/component/ComponentType;Ljava/lang/Object;)Lnet/minecraft/enchantment/Enchantment$Builder;
 *   Lnet/minecraft/loot/condition/WeatherCheckLootCondition;create()Lnet/minecraft/loot/condition/WeatherCheckLootCondition$Builder;
 *   Lnet/minecraft/loot/condition/WeatherCheckLootCondition$Builder;thundering(Z)Lnet/minecraft/loot/condition/WeatherCheckLootCondition$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;location(Lnet/minecraft/predicate/entity/LocationPredicate$Builder;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/predicate/entity/EntityPredicate$Builder;type(Lnet/minecraft/registry/RegistryEntryLookup;Lnet/minecraft/entity/EntityType;)Lnet/minecraft/predicate/entity/EntityPredicate$Builder;
 *   Lnet/minecraft/loot/condition/LocationCheckLootCondition;builder(Lnet/minecraft/predicate/entity/LocationPredicate$Builder;)Lnet/minecraft/loot/condition/LootCondition$Builder;
 *   Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;lookup(Ljava/util/List;Lnet/minecraft/enchantment/EnchantmentLevelBasedValue;)Lnet/minecraft/enchantment/EnchantmentLevelBasedValue$Lookup;
 *   Lnet/minecraft/util/collection/Pool;empty()Lnet/minecraft/util/collection/Pool;
 *   Lnet/minecraft/predicate/entity/MovementPredicate;fallDistance(Lnet/minecraft/predicate/NumberRange$DoubleRange;)Lnet/minecraft/predicate/entity/MovementPredicate;
 *   Lnet/minecraft/enchantment/Enchantment$Builder;build(Lnet/minecraft/util/Identifier;)Lnet/minecraft/enchantment/Enchantment;
 *   Lnet/minecraft/registry/Registerable;register(Lnet/minecraft/registry/RegistryKey;Ljava/lang/Object;)Lnet/minecraft/registry/entry/RegistryEntry$Reference;
 *   Lnet/minecraft/registry/RegistryKey;of(Lnet/minecraft/registry/RegistryKey;Lnet/minecraft/util/Identifier;)Lnet/minecraft/registry/RegistryKey;
 *
 * Internal private/static methods:
 *   Lnet/minecraft/enchantment/Enchantments;register(Lnet/minecraft/registry/Registerable;Lnet/minecraft/registry/RegistryKey;Lnet/minecraft/enchantment/Enchantment$Builder;)V
 *   Lnet/minecraft/enchantment/Enchantments;of(Ljava/lang/String;)Lnet/minecraft/registry/RegistryKey;
 */
package net.minecraft.enchantment;

import java.util.List;
import java.util.Optional;
import java.util.function.Function;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.component.EnchantmentEffectComponentTypes;
import net.minecraft.component.type.AttributeModifierSlot;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.enchantment.EnchantmentLevelBasedValue;
import net.minecraft.enchantment.effect.AllOfEnchantmentEffects;
import net.minecraft.enchantment.effect.AttributeEnchantmentEffect;
import net.minecraft.enchantment.effect.DamageImmunityEnchantmentEffect;
import net.minecraft.enchantment.effect.EnchantmentEffectTarget;
import net.minecraft.enchantment.effect.entity.ApplyMobEffectEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.ChangeItemDamageEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.DamageEntityEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.ExplodeEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.IgniteEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.PlaySoundEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.ReplaceDiskEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.SpawnParticlesEnchantmentEffect;
import net.minecraft.enchantment.effect.entity.SummonEntityEnchantmentEffect;
import net.minecraft.enchantment.effect.value.AddEnchantmentEffect;
import net.minecraft.enchantment.effect.value.MultiplyEnchantmentEffect;
import net.minecraft.enchantment.effect.value.RemoveBinomialEnchantmentEffect;
import net.minecraft.enchantment.effect.value.SetEnchantmentEffect;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.attribute.EntityAttributeModifier;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.damage.DamageType;
import net.minecraft.entity.damage.DamageTypes;
import net.minecraft.entity.effect.StatusEffects;
import net.minecraft.fluid.Fluids;
import net.minecraft.item.CrossbowItem;
import net.minecraft.item.Item;
import net.minecraft.item.Items;
import net.minecraft.loot.condition.AllOfLootCondition;
import net.minecraft.loot.condition.AnyOfLootCondition;
import net.minecraft.loot.condition.DamageSourcePropertiesLootCondition;
import net.minecraft.loot.condition.EnchantmentActiveCheckLootCondition;
import net.minecraft.loot.condition.EntityPropertiesLootCondition;
import net.minecraft.loot.condition.InvertedLootCondition;
import net.minecraft.loot.condition.LocationCheckLootCondition;
import net.minecraft.loot.condition.MatchToolLootCondition;
import net.minecraft.loot.condition.RandomChanceLootCondition;
import net.minecraft.loot.condition.WeatherCheckLootCondition;
import net.minecraft.loot.context.LootContext;
import net.minecraft.loot.provider.number.EnchantmentLevelLootNumberProvider;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.predicate.BlockPredicate;
import net.minecraft.predicate.NumberRange;
import net.minecraft.predicate.TagPredicate;
import net.minecraft.predicate.entity.DamageSourcePredicate;
import net.minecraft.predicate.entity.EntityFlagsPredicate;
import net.minecraft.predicate.entity.EntityPredicate;
import net.minecraft.predicate.entity.EntityTypePredicate;
import net.minecraft.predicate.entity.LocationPredicate;
import net.minecraft.predicate.entity.MovementPredicate;
import net.minecraft.predicate.item.ItemPredicate;
import net.minecraft.registry.Registerable;
import net.minecraft.registry.RegistryEntryLookup;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.entry.RegistryEntryList;
import net.minecraft.registry.tag.BlockTags;
import net.minecraft.registry.tag.DamageTypeTags;
import net.minecraft.registry.tag.EnchantmentTags;
import net.minecraft.registry.tag.EntityTypeTags;
import net.minecraft.registry.tag.ItemTags;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.Identifier;
import net.minecraft.util.collection.Pool;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.Vec3i;
import net.minecraft.util.math.floatprovider.ConstantFloatProvider;
import net.minecraft.util.math.floatprovider.UniformFloatProvider;
import net.minecraft.world.World;
import net.minecraft.world.event.GameEvent;
import net.minecraft.world.gen.blockpredicate.BlockPredicate;
import net.minecraft.world.gen.stateprovider.BlockStateProvider;

public class Enchantments {
    public static final RegistryKey<Enchantment> PROTECTION = Enchantments.of("protection");
    public static final RegistryKey<Enchantment> FIRE_PROTECTION = Enchantments.of("fire_protection");
    public static final RegistryKey<Enchantment> FEATHER_FALLING = Enchantments.of("feather_falling");
    public static final RegistryKey<Enchantment> BLAST_PROTECTION = Enchantments.of("blast_protection");
    public static final RegistryKey<Enchantment> PROJECTILE_PROTECTION = Enchantments.of("projectile_protection");
    public static final RegistryKey<Enchantment> RESPIRATION = Enchantments.of("respiration");
    public static final RegistryKey<Enchantment> AQUA_AFFINITY = Enchantments.of("aqua_affinity");
    public static final RegistryKey<Enchantment> THORNS = Enchantments.of("thorns");
    public static final RegistryKey<Enchantment> DEPTH_STRIDER = Enchantments.of("depth_strider");
    public static final RegistryKey<Enchantment> FROST_WALKER = Enchantments.of("frost_walker");
    public static final RegistryKey<Enchantment> BINDING_CURSE = Enchantments.of("binding_curse");
    public static final RegistryKey<Enchantment> SOUL_SPEED = Enchantments.of("soul_speed");
    public static final RegistryKey<Enchantment> SWIFT_SNEAK = Enchantments.of("swift_sneak");
    public static final RegistryKey<Enchantment> SHARPNESS = Enchantments.of("sharpness");
    public static final RegistryKey<Enchantment> SMITE = Enchantments.of("smite");
    public static final RegistryKey<Enchantment> BANE_OF_ARTHROPODS = Enchantments.of("bane_of_arthropods");
    public static final RegistryKey<Enchantment> KNOCKBACK = Enchantments.of("knockback");
    public static final RegistryKey<Enchantment> FIRE_ASPECT = Enchantments.of("fire_aspect");
    public static final RegistryKey<Enchantment> LOOTING = Enchantments.of("looting");
    public static final RegistryKey<Enchantment> SWEEPING_EDGE = Enchantments.of("sweeping_edge");
    public static final RegistryKey<Enchantment> EFFICIENCY = Enchantments.of("efficiency");
    public static final RegistryKey<Enchantment> SILK_TOUCH = Enchantments.of("silk_touch");
    public static final RegistryKey<Enchantment> UNBREAKING = Enchantments.of("unbreaking");
    public static final RegistryKey<Enchantment> FORTUNE = Enchantments.of("fortune");
    public static final RegistryKey<Enchantment> POWER = Enchantments.of("power");
    public static final RegistryKey<Enchantment> PUNCH = Enchantments.of("punch");
    public static final RegistryKey<Enchantment> FLAME = Enchantments.of("flame");
    public static final RegistryKey<Enchantment> INFINITY = Enchantments.of("infinity");
    public static final RegistryKey<Enchantment> LUCK_OF_THE_SEA = Enchantments.of("luck_of_the_sea");
    public static final RegistryKey<Enchantment> LURE = Enchantments.of("lure");
    public static final RegistryKey<Enchantment> LOYALTY = Enchantments.of("loyalty");
    public static final RegistryKey<Enchantment> IMPALING = Enchantments.of("impaling");
    public static final RegistryKey<Enchantment> RIPTIDE = Enchantments.of("riptide");
    public static final RegistryKey<Enchantment> CHANNELING = Enchantments.of("channeling");
    public static final RegistryKey<Enchantment> MULTISHOT = Enchantments.of("multishot");
    public static final RegistryKey<Enchantment> QUICK_CHARGE = Enchantments.of("quick_charge");
    public static final RegistryKey<Enchantment> PIERCING = Enchantments.of("piercing");
    public static final RegistryKey<Enchantment> DENSITY = Enchantments.of("density");
    public static final RegistryKey<Enchantment> BREACH = Enchantments.of("breach");
    public static final RegistryKey<Enchantment> WIND_BURST = Enchantments.of("wind_burst");
    public static final RegistryKey<Enchantment> MENDING = Enchantments.of("mending");
    public static final RegistryKey<Enchantment> VANISHING_CURSE = Enchantments.of("vanishing_curse");

    public static void bootstrap(Registerable<Enchantment> registry) {
        RegistryEntryLookup<DamageType> lv = registry.getRegistryLookup(RegistryKeys.DAMAGE_TYPE);
        RegistryEntryLookup<Enchantment> lv2 = registry.getRegistryLookup(RegistryKeys.ENCHANTMENT);
        RegistryEntryLookup<Item> lv3 = registry.getRegistryLookup(RegistryKeys.ITEM);
        RegistryEntryLookup<Block> lv4 = registry.getRegistryLookup(RegistryKeys.BLOCK);
        RegistryEntryLookup<EntityType<?>> lv5 = registry.getRegistryLookup(RegistryKeys.ENTITY_TYPE);
        Enchantments.register(registry, PROTECTION, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 10, 4, Enchantment.leveledCost(1, 11), Enchantment.leveledCost(12, 11), 1, AttributeModifierSlot.ARMOR)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.ARMOR_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_PROTECTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f)), DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY)))));
        Enchantments.register(registry, FIRE_PROTECTION, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 5, 4, Enchantment.leveledCost(10, 8), Enchantment.leveledCost(18, 8), 2, AttributeModifierSlot.ARMOR)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.ARMOR_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_PROTECTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.0f)), AllOfLootCondition.builder(DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.expected(DamageTypeTags.IS_FIRE)).tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY))))).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.fire_protection"), EntityAttributes.BURNING_TIME, EnchantmentLevelBasedValue.linear(-0.15f), EntityAttributeModifier.Operation.ADD_MULTIPLIED_BASE)));
        Enchantments.register(registry, FEATHER_FALLING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 5, 4, Enchantment.leveledCost(5, 6), Enchantment.leveledCost(11, 6), 2, AttributeModifierSlot.ARMOR)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_PROTECTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(3.0f)), DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.expected(DamageTypeTags.IS_FALL)).tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY)))));
        Enchantments.register(registry, BLAST_PROTECTION, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 2, 4, Enchantment.leveledCost(5, 8), Enchantment.leveledCost(13, 8), 4, AttributeModifierSlot.ARMOR)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.ARMOR_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_PROTECTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.0f)), DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.expected(DamageTypeTags.IS_EXPLOSION)).tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY)))).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.blast_protection"), EntityAttributes.EXPLOSION_KNOCKBACK_RESISTANCE, EnchantmentLevelBasedValue.linear(0.15f), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, PROJECTILE_PROTECTION, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), 5, 4, Enchantment.leveledCost(3, 6), Enchantment.leveledCost(9, 6), 2, AttributeModifierSlot.ARMOR)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.ARMOR_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_PROTECTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.0f)), DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.expected(DamageTypeTags.IS_PROJECTILE)).tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY)))));
        Enchantments.register(registry, RESPIRATION, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.HEAD_ARMOR_ENCHANTABLE), 2, 3, Enchantment.leveledCost(10, 10), Enchantment.leveledCost(40, 10), 4, AttributeModifierSlot.HEAD)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.respiration"), EntityAttributes.OXYGEN_BONUS, EnchantmentLevelBasedValue.linear(1.0f), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, AQUA_AFFINITY, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.HEAD_ARMOR_ENCHANTABLE), 2, 1, Enchantment.constantCost(1), Enchantment.constantCost(41), 4, AttributeModifierSlot.HEAD)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.aqua_affinity"), EntityAttributes.SUBMERGED_MINING_SPEED, EnchantmentLevelBasedValue.linear(4.0f), EntityAttributeModifier.Operation.ADD_MULTIPLIED_TOTAL)));
        Enchantments.register(registry, THORNS, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.ARMOR_ENCHANTABLE), lv3.getOrThrow(ItemTags.CHEST_ARMOR_ENCHANTABLE), 1, 3, Enchantment.leveledCost(10, 20), Enchantment.leveledCost(60, 20), 8, AttributeModifierSlot.ANY)).addEffect(EnchantmentEffectComponentTypes.POST_ATTACK, EnchantmentEffectTarget.VICTIM, EnchantmentEffectTarget.ATTACKER, AllOfEnchantmentEffects.allOf(new DamageEntityEnchantmentEffect(EnchantmentLevelBasedValue.constant(1.0f), EnchantmentLevelBasedValue.constant(5.0f), lv.getOrThrow(DamageTypes.THORNS)), new ChangeItemDamageEnchantmentEffect(EnchantmentLevelBasedValue.constant(2.0f))), RandomChanceLootCondition.builder(EnchantmentLevelLootNumberProvider.create(EnchantmentLevelBasedValue.linear(0.15f)))));
        Enchantments.register(registry, DEPTH_STRIDER, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 2, 3, Enchantment.leveledCost(10, 10), Enchantment.leveledCost(25, 10), 4, AttributeModifierSlot.FEET)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.BOOTS_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.depth_strider"), EntityAttributes.WATER_MOVEMENT_EFFICIENCY, EnchantmentLevelBasedValue.linear(0.33333334f), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, FROST_WALKER, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 2, 2, Enchantment.leveledCost(10, 10), Enchantment.leveledCost(25, 10), 4, AttributeModifierSlot.FEET)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.BOOTS_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE_IMMUNITY, DamageImmunityEnchantmentEffect.INSTANCE, DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().tag(TagPredicate.expected(DamageTypeTags.BURN_FROM_STEPPING)).tag(TagPredicate.unexpected(DamageTypeTags.BYPASSES_INVULNERABILITY)))).addEffect(EnchantmentEffectComponentTypes.LOCATION_CHANGED, new ReplaceDiskEnchantmentEffect(new EnchantmentLevelBasedValue.Clamped(EnchantmentLevelBasedValue.linear(3.0f, 1.0f), 0.0f, 16.0f), EnchantmentLevelBasedValue.constant(1.0f), new Vec3i(0, -1, 0), Optional.of(BlockPredicate.allOf(BlockPredicate.matchingBlockTag(new Vec3i(0, 1, 0), BlockTags.AIR), BlockPredicate.matchingBlocks(Blocks.WATER), BlockPredicate.matchingFluids(Fluids.WATER), BlockPredicate.unobstructed())), BlockStateProvider.of(Blocks.FROSTED_ICE), Optional.of(GameEvent.BLOCK_PLACE)), AllOfLootCondition.builder(EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().flags(EntityFlagsPredicate.Builder.create().onGround(true))), InvertedLootCondition.builder(EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().vehicle(EntityPredicate.Builder.create()))))));
        Enchantments.register(registry, BINDING_CURSE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.EQUIPPABLE_ENCHANTABLE), 1, 1, Enchantment.constantCost(25), Enchantment.constantCost(50), 8, AttributeModifierSlot.ARMOR)).addEffect(EnchantmentEffectComponentTypes.PREVENT_ARMOR_CHANGE));
        EntityPredicate.Builder lv6 = EntityPredicate.Builder.create().periodicTick(5).flags(EntityFlagsPredicate.Builder.create().flying(false).onGround(true)).movement(MovementPredicate.horizontalSpeed(NumberRange.DoubleRange.atLeast(1.0E-5f))).movementAffectedBy(LocationPredicate.Builder.create().block(BlockPredicate.Builder.create().tag(lv4, BlockTags.SOUL_SPEED_BLOCKS)));
        AllOfLootCondition.Builder lv7 = AllOfLootCondition.builder(InvertedLootCondition.builder(EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().vehicle(EntityPredicate.Builder.create()))), AnyOfLootCondition.builder(AllOfLootCondition.builder(EnchantmentActiveCheckLootCondition.requireActive(), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().flags(EntityFlagsPredicate.Builder.create().flying(false))), AnyOfLootCondition.builder(EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().movementAffectedBy(LocationPredicate.Builder.create().block(BlockPredicate.Builder.create().tag(lv4, BlockTags.SOUL_SPEED_BLOCKS)))), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().flags(EntityFlagsPredicate.Builder.create().onGround(false)).build()))), AllOfLootCondition.builder(EnchantmentActiveCheckLootCondition.requireInactive(), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().movementAffectedBy(LocationPredicate.Builder.create().block(BlockPredicate.Builder.create().tag(lv4, BlockTags.SOUL_SPEED_BLOCKS))).flags(EntityFlagsPredicate.Builder.create().flying(false))))));
        Enchantments.register(registry, SOUL_SPEED, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FOOT_ARMOR_ENCHANTABLE), 1, 3, Enchantment.leveledCost(10, 10), Enchantment.leveledCost(25, 10), 8, AttributeModifierSlot.FEET)).addEffect(EnchantmentEffectComponentTypes.LOCATION_CHANGED, AllOfEnchantmentEffects.allOf(new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.soul_speed"), EntityAttributes.MOVEMENT_SPEED, EnchantmentLevelBasedValue.linear(0.0405f, 0.0105f), EntityAttributeModifier.Operation.ADD_VALUE), new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.soul_speed"), EntityAttributes.MOVEMENT_EFFICIENCY, EnchantmentLevelBasedValue.constant(1.0f), EntityAttributeModifier.Operation.ADD_VALUE)), lv7).addEffect(EnchantmentEffectComponentTypes.LOCATION_CHANGED, new ChangeItemDamageEnchantmentEffect(EnchantmentLevelBasedValue.constant(1.0f)), AllOfLootCondition.builder(RandomChanceLootCondition.builder(EnchantmentLevelLootNumberProvider.create(EnchantmentLevelBasedValue.constant(0.04f))), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().flags(EntityFlagsPredicate.Builder.create().onGround(true)).movementAffectedBy(LocationPredicate.Builder.create().block(BlockPredicate.Builder.create().tag(lv4, BlockTags.SOUL_SPEED_BLOCKS)))))).addEffect(EnchantmentEffectComponentTypes.TICK, new SpawnParticlesEnchantmentEffect(ParticleTypes.SOUL, SpawnParticlesEnchantmentEffect.withinBoundingBox(), SpawnParticlesEnchantmentEffect.entityPosition(0.1f), SpawnParticlesEnchantmentEffect.scaledVelocity(-0.2f), SpawnParticlesEnchantmentEffect.fixedVelocity(ConstantFloatProvider.create(0.1f)), ConstantFloatProvider.create(1.0f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, lv6)).addEffect(EnchantmentEffectComponentTypes.TICK, new PlaySoundEnchantmentEffect(SoundEvents.PARTICLE_SOUL_ESCAPE, ConstantFloatProvider.create(0.6f), UniformFloatProvider.create(0.6f, 1.0f)), AllOfLootCondition.builder(RandomChanceLootCondition.builder(0.35f), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, lv6))));
        Enchantments.register(registry, SWIFT_SNEAK, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.LEG_ARMOR_ENCHANTABLE), 1, 3, Enchantment.leveledCost(25, 25), Enchantment.leveledCost(75, 25), 8, AttributeModifierSlot.LEGS)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.swift_sneak"), EntityAttributes.SNEAKING_SPEED, EnchantmentLevelBasedValue.linear(0.15f), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, SHARPNESS, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.SHARP_WEAPON_ENCHANTABLE), lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 10, 5, Enchantment.leveledCost(1, 11), Enchantment.leveledCost(21, 11), 1, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f, 0.5f))));
        Enchantments.register(registry, SMITE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.WEAPON_ENCHANTABLE), lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 5, 5, Enchantment.leveledCost(5, 8), Enchantment.leveledCost(25, 8), 2, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.5f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().type(EntityTypePredicate.create(lv5, EntityTypeTags.SENSITIVE_TO_SMITE)))));
        Enchantments.register(registry, BANE_OF_ARTHROPODS, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.WEAPON_ENCHANTABLE), lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 5, 5, Enchantment.leveledCost(5, 8), Enchantment.leveledCost(25, 8), 2, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.5f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().type(EntityTypePredicate.create(lv5, EntityTypeTags.SENSITIVE_TO_BANE_OF_ARTHROPODS)))).addEffect(EnchantmentEffectComponentTypes.POST_ATTACK, EnchantmentEffectTarget.ATTACKER, EnchantmentEffectTarget.VICTIM, new ApplyMobEffectEnchantmentEffect(RegistryEntryList.of(StatusEffects.SLOWNESS), EnchantmentLevelBasedValue.constant(1.5f), EnchantmentLevelBasedValue.linear(1.5f, 0.5f), EnchantmentLevelBasedValue.constant(3.0f), EnchantmentLevelBasedValue.constant(3.0f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().type(EntityTypePredicate.create(lv5, EntityTypeTags.SENSITIVE_TO_BANE_OF_ARTHROPODS))).and(DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().isDirect(true)))));
        Enchantments.register(registry, KNOCKBACK, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 5, 2, Enchantment.leveledCost(5, 20), Enchantment.leveledCost(55, 20), 2, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.KNOCKBACK, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f))));
        Enchantments.register(registry, FIRE_ASPECT, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FIRE_ASPECT_ENCHANTABLE), lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 2, 2, Enchantment.leveledCost(10, 20), Enchantment.leveledCost(60, 20), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.POST_ATTACK, EnchantmentEffectTarget.ATTACKER, EnchantmentEffectTarget.VICTIM, new IgniteEnchantmentEffect(EnchantmentLevelBasedValue.linear(4.0f)), DamageSourcePropertiesLootCondition.builder(DamageSourcePredicate.Builder.create().isDirect(true))));
        Enchantments.register(registry, LOOTING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 2, 3, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.EQUIPMENT_DROPS, EnchantmentEffectTarget.ATTACKER, EnchantmentEffectTarget.VICTIM, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(0.01f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.ATTACKER, EntityPredicate.Builder.create().type(EntityTypePredicate.create(lv5, EntityType.PLAYER)))));
        Enchantments.register(registry, SWEEPING_EDGE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.SWORD_ENCHANTABLE), 2, 3, Enchantment.leveledCost(5, 9), Enchantment.leveledCost(20, 9), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.sweeping_edge"), EntityAttributes.SWEEPING_DAMAGE_RATIO, new EnchantmentLevelBasedValue.Fraction(EnchantmentLevelBasedValue.linear(1.0f), EnchantmentLevelBasedValue.linear(2.0f, 1.0f)), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, EFFICIENCY, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MINING_ENCHANTABLE), 10, 5, Enchantment.leveledCost(1, 10), Enchantment.leveledCost(51, 10), 1, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.ATTRIBUTES, new AttributeEnchantmentEffect(Identifier.ofVanilla("enchantment.efficiency"), EntityAttributes.MINING_EFFICIENCY, new EnchantmentLevelBasedValue.LevelsSquared(1.0f), EntityAttributeModifier.Operation.ADD_VALUE)));
        Enchantments.register(registry, SILK_TOUCH, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MINING_LOOT_ENCHANTABLE), 1, 1, Enchantment.constantCost(15), Enchantment.constantCost(65), 8, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.MINING_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.BLOCK_EXPERIENCE, new SetEnchantmentEffect(EnchantmentLevelBasedValue.constant(0.0f))));
        Enchantments.register(registry, UNBREAKING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.DURABILITY_ENCHANTABLE), 5, 3, Enchantment.leveledCost(5, 8), Enchantment.leveledCost(55, 8), 2, AttributeModifierSlot.ANY)).addEffect(EnchantmentEffectComponentTypes.ITEM_DAMAGE, new RemoveBinomialEnchantmentEffect(new EnchantmentLevelBasedValue.Fraction(EnchantmentLevelBasedValue.linear(2.0f), EnchantmentLevelBasedValue.linear(10.0f, 5.0f))), MatchToolLootCondition.builder(ItemPredicate.Builder.create().tag(lv3, ItemTags.ARMOR_ENCHANTABLE))).addEffect(EnchantmentEffectComponentTypes.ITEM_DAMAGE, new RemoveBinomialEnchantmentEffect(new EnchantmentLevelBasedValue.Fraction(EnchantmentLevelBasedValue.linear(1.0f), EnchantmentLevelBasedValue.linear(2.0f, 1.0f))), InvertedLootCondition.builder(MatchToolLootCondition.builder(ItemPredicate.Builder.create().tag(lv3, ItemTags.ARMOR_ENCHANTABLE)))));
        Enchantments.register(registry, FORTUNE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MINING_LOOT_ENCHANTABLE), 2, 3, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.MINING_EXCLUSIVE_SET)));
        Enchantments.register(registry, POWER, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.BOW_ENCHANTABLE), 10, 5, Enchantment.leveledCost(1, 10), Enchantment.leveledCost(16, 10), 1, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.DAMAGE, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f, 0.5f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.DIRECT_ATTACKER, EntityPredicate.Builder.create().type(lv5, EntityTypeTags.ARROWS).build())));
        Enchantments.register(registry, PUNCH, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.BOW_ENCHANTABLE), 2, 2, Enchantment.leveledCost(12, 20), Enchantment.leveledCost(37, 20), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.KNOCKBACK, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.DIRECT_ATTACKER, EntityPredicate.Builder.create().type(lv5, EntityTypeTags.ARROWS).build())));
        Enchantments.register(registry, FLAME, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.BOW_ENCHANTABLE), 2, 1, Enchantment.constantCost(20), Enchantment.constantCost(50), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.PROJECTILE_SPAWNED, new IgniteEnchantmentEffect(EnchantmentLevelBasedValue.constant(100.0f))));
        Enchantments.register(registry, INFINITY, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.BOW_ENCHANTABLE), 1, 1, Enchantment.constantCost(20), Enchantment.constantCost(50), 8, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.BOW_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.AMMO_USE, new SetEnchantmentEffect(EnchantmentLevelBasedValue.constant(0.0f)), MatchToolLootCondition.builder(ItemPredicate.Builder.create().items(lv3, Items.ARROW))));
        Enchantments.register(registry, LUCK_OF_THE_SEA, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FISHING_ENCHANTABLE), 2, 3, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.FISHING_LUCK_BONUS, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f))));
        Enchantments.register(registry, LURE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.FISHING_ENCHANTABLE), 2, 3, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.FISHING_TIME_REDUCTION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(5.0f))));
        Enchantments.register(registry, LOYALTY, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.TRIDENT_ENCHANTABLE), 5, 3, Enchantment.leveledCost(12, 7), Enchantment.constantCost(50), 2, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.TRIDENT_RETURN_ACCELERATION, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f))));
        Enchantments.register(registry, IMPALING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.TRIDENT_ENCHANTABLE), 2, 5, Enchantment.leveledCost(1, 8), Enchantment.leveledCost(21, 8), 4, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.DAMAGE, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.5f)), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().type(EntityTypePredicate.create(lv5, EntityTypeTags.SENSITIVE_TO_IMPALING)).build())));
        Enchantments.register(registry, RIPTIDE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.TRIDENT_ENCHANTABLE), 2, 3, Enchantment.leveledCost(17, 7), Enchantment.constantCost(50), 4, AttributeModifierSlot.HAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.RIPTIDE_EXCLUSIVE_SET)).addNonListEffect(EnchantmentEffectComponentTypes.TRIDENT_SPIN_ATTACK_STRENGTH, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.5f, 0.75f))).addNonListEffect(EnchantmentEffectComponentTypes.TRIDENT_SOUND, List.of(SoundEvents.ITEM_TRIDENT_RIPTIDE_1, SoundEvents.ITEM_TRIDENT_RIPTIDE_2, SoundEvents.ITEM_TRIDENT_RIPTIDE_3)));
        Enchantments.register(registry, CHANNELING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.TRIDENT_ENCHANTABLE), 1, 1, Enchantment.constantCost(25), Enchantment.constantCost(50), 8, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.POST_ATTACK, EnchantmentEffectTarget.ATTACKER, EnchantmentEffectTarget.VICTIM, AllOfEnchantmentEffects.allOf(new SummonEntityEnchantmentEffect(RegistryEntryList.of(EntityType.LIGHTNING_BOLT.getRegistryEntry()), false), new PlaySoundEnchantmentEffect(SoundEvents.ITEM_TRIDENT_THUNDER, ConstantFloatProvider.create(5.0f), ConstantFloatProvider.create(1.0f))), AllOfLootCondition.builder(WeatherCheckLootCondition.create().thundering(true), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().location(LocationPredicate.Builder.create().canSeeSky(true))), EntityPropertiesLootCondition.builder(LootContext.EntityReference.DIRECT_ATTACKER, EntityPredicate.Builder.create().type(lv5, EntityType.TRIDENT)))).addEffect(EnchantmentEffectComponentTypes.HIT_BLOCK, AllOfEnchantmentEffects.allOf(new SummonEntityEnchantmentEffect(RegistryEntryList.of(EntityType.LIGHTNING_BOLT.getRegistryEntry()), false), new PlaySoundEnchantmentEffect(SoundEvents.ITEM_TRIDENT_THUNDER, ConstantFloatProvider.create(5.0f), ConstantFloatProvider.create(1.0f))), AllOfLootCondition.builder(WeatherCheckLootCondition.create().thundering(true), EntityPropertiesLootCondition.builder(LootContext.EntityReference.THIS, EntityPredicate.Builder.create().type(lv5, EntityType.TRIDENT)), LocationCheckLootCondition.builder(LocationPredicate.Builder.create().canSeeSky(true).block(BlockPredicate.Builder.create().tag(lv4, BlockTags.LIGHTNING_RODS))))));
        Enchantments.register(registry, MULTISHOT, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.CROSSBOW_ENCHANTABLE), 2, 1, Enchantment.constantCost(20), Enchantment.constantCost(50), 4, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.CROSSBOW_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.PROJECTILE_COUNT, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(2.0f))).addEffect(EnchantmentEffectComponentTypes.PROJECTILE_SPREAD, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(10.0f))));
        Enchantments.register(registry, QUICK_CHARGE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.CROSSBOW_ENCHANTABLE), 5, 3, Enchantment.leveledCost(12, 20), Enchantment.constantCost(50), 2, AttributeModifierSlot.MAINHAND, AttributeModifierSlot.OFFHAND)).addNonListEffect(EnchantmentEffectComponentTypes.CROSSBOW_CHARGE_TIME, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(-0.25f))).addNonListEffect(EnchantmentEffectComponentTypes.CROSSBOW_CHARGING_SOUNDS, List.of(new CrossbowItem.LoadingSounds(Optional.of(SoundEvents.ITEM_CROSSBOW_QUICK_CHARGE_1), Optional.empty(), Optional.of(SoundEvents.ITEM_CROSSBOW_LOADING_END)), new CrossbowItem.LoadingSounds(Optional.of(SoundEvents.ITEM_CROSSBOW_QUICK_CHARGE_2), Optional.empty(), Optional.of(SoundEvents.ITEM_CROSSBOW_LOADING_END)), new CrossbowItem.LoadingSounds(Optional.of(SoundEvents.ITEM_CROSSBOW_QUICK_CHARGE_3), Optional.empty(), Optional.of(SoundEvents.ITEM_CROSSBOW_LOADING_END)))));
        Enchantments.register(registry, PIERCING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.CROSSBOW_ENCHANTABLE), 10, 4, Enchantment.leveledCost(1, 10), Enchantment.constantCost(50), 1, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.CROSSBOW_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.PROJECTILE_PIERCING, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(1.0f))));
        Enchantments.register(registry, DENSITY, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MACE_ENCHANTABLE), 5, 5, Enchantment.leveledCost(5, 8), Enchantment.leveledCost(25, 8), 2, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.SMASH_DAMAGE_PER_FALLEN_BLOCK, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(0.5f))));
        Enchantments.register(registry, BREACH, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MACE_ENCHANTABLE), 2, 4, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).exclusiveSet(lv2.getOrThrow(EnchantmentTags.DAMAGE_EXCLUSIVE_SET)).addEffect(EnchantmentEffectComponentTypes.ARMOR_EFFECTIVENESS, new AddEnchantmentEffect(EnchantmentLevelBasedValue.linear(-0.15f))));
        Enchantments.register(registry, WIND_BURST, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.MACE_ENCHANTABLE), 2, 3, Enchantment.leveledCost(15, 9), Enchantment.leveledCost(65, 9), 4, AttributeModifierSlot.MAINHAND)).addEffect(EnchantmentEffectComponentTypes.POST_ATTACK, EnchantmentEffectTarget.ATTACKER, EnchantmentEffectTarget.ATTACKER, new ExplodeEnchantmentEffect(false, Optional.empty(), Optional.of(EnchantmentLevelBasedValue.lookup(List.of(Float.valueOf(1.2f), Float.valueOf(1.75f), Float.valueOf(2.2f)), EnchantmentLevelBasedValue.linear(1.5f, 0.35f))), lv4.getOptional(BlockTags.BLOCKS_WIND_CHARGE_EXPLOSIONS).map(Function.identity()), Vec3d.ZERO, EnchantmentLevelBasedValue.constant(3.5f), false, World.ExplosionSourceType.TRIGGER, ParticleTypes.GUST_EMITTER_SMALL, ParticleTypes.GUST_EMITTER_LARGE, Pool.empty(), SoundEvents.ENTITY_WIND_CHARGE_WIND_BURST), EntityPropertiesLootCondition.builder(LootContext.EntityReference.DIRECT_ATTACKER, EntityPredicate.Builder.create().flags(EntityFlagsPredicate.Builder.create().flying(false)).movement(MovementPredicate.fallDistance(NumberRange.DoubleRange.atLeast(1.5))))));
        Enchantments.register(registry, MENDING, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.DURABILITY_ENCHANTABLE), 2, 1, Enchantment.leveledCost(25, 25), Enchantment.leveledCost(75, 25), 4, AttributeModifierSlot.ANY)).addEffect(EnchantmentEffectComponentTypes.REPAIR_WITH_XP, new MultiplyEnchantmentEffect(EnchantmentLevelBasedValue.constant(2.0f))));
        Enchantments.register(registry, VANISHING_CURSE, Enchantment.builder(Enchantment.definition(lv3.getOrThrow(ItemTags.VANISHING_ENCHANTABLE), 1, 1, Enchantment.constantCost(25), Enchantment.constantCost(50), 8, AttributeModifierSlot.ANY)).addEffect(EnchantmentEffectComponentTypes.PREVENT_EQUIPMENT_DROP));
    }

    private static void register(Registerable<Enchantment> registry, RegistryKey<Enchantment> key, Enchantment.Builder builder) {
        registry.register(key, builder.build(key.getValue()));
    }

    private static RegistryKey<Enchantment> of(String id) {
        return RegistryKey.of(RegistryKeys.ENCHANTMENT, Identifier.ofVanilla(id));
    }
}

